name: Test Registry

on:
  push:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Make script executable
        run: chmod +x ./test_registries.sh
      
      - name: Test Registries and Update README
        run: ./test_registries.sh

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: /tmp/registry-test-*.log
            
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update registry test results and top 3 mirrors"; git push)
